### ISSUE TITLE
Fetch data for "Wave 3 timeline" widget on dashboard

### ISSUE THREAD

**Issue by theflexbird** [OpusCapita/onboarding#105]
![zrzut ekranu z 2017-05-09 13-42-42](https://cloud.githubusercontent.com/assets/1525388/25849211/da3c282c-34bd-11e7-8ec0-3a6839a3e90c.png)

[Parent task](https://github.com/OpusCapita/onboarding/issues/68)

**Comment by nczeranka** [comment]
Still requested?
If yes, what are the requirements for the new widget?
