### ISSUE TITLE
New campaign does not set customerId

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#121]
Create new campaign with customerId = user.customerId (the user's tenant)

**Comment by patrykkopycinski** [comment]
@gr4per could you check it again? seems to be working properly

**Comment by gr4per** [comment]
If you checked on dev, it is working properly cause I modified schema last friday to set default "ncc" on column customerId.

**Comment by gr4per** [comment]
| Campaign | CREATE TABLE `Campaign` (
  `campaignId` varchar(30) NOT NULL,
  `description` varchar(50) DEFAULT NULL,
  `startsOn` datetime DEFAULT NULL,
  `endsOn` datetime DEFAULT NULL,
  `status` varchar(30) NOT NULL,
  `campaignType` varchar(30) NOT NULL,
  `companyId` varchar(30) DEFAULT NULL,
  `customerId` varchar(30) DEFAULT 'ncc',
  PRIMARY KEY (`campaignId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 |
+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> alter table Campaign alter column customerId drop default;
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> show create table Campaign;
+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table    | Create Table                                                                                                                                                                                                                                                                                                                                                                                    |
+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Campaign | CREATE TABLE `Campaign` (
  `campaignId` varchar(30) NOT NULL,
  `description` varchar(50) DEFAULT NULL,
  `startsOn` datetime DEFAULT NULL,
  `endsOn` datetime DEFAULT NULL,
  `status` varchar(30) NOT NULL,
  `campaignType` varchar(30) NOT NULL,
  `companyId` varchar(30) DEFAULT NULL,
  `customerId` varchar(30),
  PRIMARY KEY (`campaignId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 |

Try now

**Comment by gr4per** [comment]
Seems really working now.
