### ISSUE TITLE
Fix campaign DB schema

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#131]
* drop primary key from campaignId
* introduce new column id BIGINT primary key auto increment
* rename column campaignId to name
* add unique index on customer, name

**Comment by celber** [comment]
ignore reference above, we do not know why i is here. Maybe a bug

**Comment by gr4per** [comment]
We need to take care about several things in order to not break app:
* campaigns/:campaignId endpoint
  since we will have a new primary key (SN) we could either use that or refactor to include tenantId
  campaigns/_current/:name
  the question is whether tenant is explicitly required as we have no use case for accessing campaigns of a different tenant.
  however, explicit tenantId is more future proof

## server routes
* /campaings endpoint, same

* /campaigns/:campaignId/contacts
  same, we have to make it explicit :tenantid/:name to reflect the composite key or use the numeric key

* /campaigns/:campaignId/contacts/:email
  same. not clear what this one is used for though ?

## workflow.js
* /public/landingpage/:campaignId/:contactId
since campaignId is gone, we need numeric key or :tenantId/:name

* /public/transition/:campaignId/:contactId
  same

* /api/campaigns/start/:campaignId
  same
