### ISSUE TITLE
Create basic integration tests

### ISSUE THREAD

**Issue by celber** [OpusCapita/onboarding#146]
Do basci tests using https://github.com/OpusCapitaBusinessNetwork/selenium-server

Remember: it will probably changed to test cafe in future

**Comment by patrykkopycinski** [comment]
https://github.com/OpusCapita/onboarding/pull/154/files#diff-1d37e48f9ceff6d8030570cd36286a61R79

i've done some stupid simple integration tests that are going through login form and check if onboarding is rendered properly
