### ISSUE TITLE
Fix connected suppliers dashboard

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#164]
Top left.
The data is the relation between customer (of current user) and any supplier, data model in einv-send service.
Probably it makes sense to implement the whole widget in einv send and just share into onboarding.
The timeline can simply be done taking createdOn into account.
Ask kwierchris for data model and implementation strategy

**Comment by gr4per** [comment]
Create in eInv-send and embed in onboarding
/einv-send/static/components/connectedSuppliers.js

**Comment by lasong** [comment]
Implemented by https://github.com/OpusCapita/onboarding/pull/213
