### ISSUE TITLE
Develop is not working

### ISSUE THREAD

**Issue by theflexbird** [OpusCapita/onboarding#166]
<img width="1279" alt="zrzut ekranu 2017-06-18 o 23 11 20" src="https://user-images.githubusercontent.com/1525388/27264372-37677248-547d-11e7-9577-779f9197a2f9.png">

**Comment by patrykkopycinski** [comment]
@sureshvarman-cronj

**Comment by sureshvarman-cronj** [comment]
The problem seems like not only with onboarding all other services are also down. need a check in dev environment, but im not even able to ssh into dev env
