### ISSUE TITLE
Campaign update gives wrong feedback

### ISSUE THREAD

**Issue by celber** [OpusCapita/onboarding#204]
![campaign editor 2017-07-06 10-45-28](https://user-images.githubusercontent.com/2181779/27903106-62c1c42a-6238-11e7-8258-515ee9565740.png)

Editing campaign works but shows error.

Steps to reproduce:
- create campaign 'delete-me'
- navigate to search view (/onboarding/)
- click on edit 'delete-me' campaign
- change description
- save

Result: Error is shown but data is successfully updated
Expected result: success confirmation is shown

**Comment by theflexbird** [comment]
@celber, I could not reproduce it.

**Comment by celber** [comment]
not valid anymore
