### ISSUE TITLE
Campaign Email not rendering properly

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#205]
![image](https://user-images.githubusercontent.com/22681804/27906390-a4bd53c0-6243-11e7-9106-2f37a6862acd.png)

in the message source code it looks like
![image](https://user-images.githubusercontent.com/22681804/27906452-dc113daa-6243-11e7-90d4-613b6e337f41.png)

**Comment by celber** [comment]
Cannot reproduce. Please retest

**Comment by kwierchris** [comment]
Should not be valid anymore.
