### ISSUE TITLE
Allow contacts without eMail

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#215]
Sub-issue of OpusCapita/businessnetwork#35

This will allow to skip eMail sending for contacts where we don't have eMail.
The intention is to still be able to monitor campaign based on externally sent invitation.

Basically a minor change. In emailSending we just advance status to "sent" in case there is no campaignContact.email configured for the contact.
this means we assume info has been sent to contact in some external way (possibly including the invitation code).

remove "required" check on campaignContact.email
Add warning here "No email is going to be sent, you have to send the invitation by external means"

Adjust importer to accept contacts without email.

**Comment by nczeranka** [comment]
businessnetwork/issues/35

**Comment by sureshvarman-cronj** [comment]
Covered already both in front-end and backend

**Comment by celber** [comment]
waits for changes
