### ISSUE TITLE
Customer id in horizontal header, needs to be name

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#216]
![image](https://user-images.githubusercontent.com/22681804/28055544-a4ece17e-6619-11e7-8f4c-bb092dca189a.png)

**Comment by kwierchris** [comment]
In order to work on this you'll have to go with the https://github.com/OpusCapita/react-components repo. Please report to me once this is finished as it has to be published on npmjs so it can be used in our services.

**Comment by kwierchris** [comment]
Done.
