### ISSUE TITLE
Rendering errors / clipping in contact editor

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#219]
![image](https://user-images.githubusercontent.com/22681804/28056691-14695876-661e-11e7-9d50-31720041c020.png)

This need to work responsively without elements clipping into/overlapping each other

**Comment by kwierchris** [comment]
Should get fixed once this is done: https://github.com/OpusCapita/onboarding/issues/269

**Comment by lasong** [comment]
Fixed with #282
