### ISSUE TITLE
Campaign editor not properly translated

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#220]
![image](https://user-images.githubusercontent.com/22681804/28056801-8ddafade-661e-11e7-9ab2-3157491d074b.png)
This is the GERMAN view
Other pages in the editor have similar issues.

**Comment by kwierchris** [comment]
The following sites are not even yet prepared for translations:

* /onboarding/edit/ncc-sob-w1/contacts (the contact list labels)
* /onboarding/edit/ncc-sob-w1/process (the headers and the launch button)

The following files have to be modified:

* /src/client/components/CampaignContacts/ContactListItem.react.js
* /src/client/containers/CampaignProcess.react.js
