### ISSUE TITLE
Tracking image displayed as broken link

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#222]
![image](https://user-images.githubusercontent.com/22681804/28057164-952a9f32-661f-11e7-8e6a-9199da3da584.png)
Fix by making it display:none or returning a white 1x1 png

**Comment by nczeranka** [comment]
E-Mail Layout was reworked with the help of Charleen.
Has to be checked that tracking is still working properly.

**Comment by kwierchris** [comment]
Not valid anymore.
