### ISSUE TITLE
Language cookie not properly set on landing page

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#224]
![image](https://user-images.githubusercontent.com/22681804/28057454-869deb1c-6620-11e7-8981-152c7d147fa0.png)
it seems it is setting whatever the browser sends as accept-language,.

Fix by onLanguageSelectionChange (drop down):
do clear OPUSCAPITA_LANGUAGE cookie
then set OPUSCAPITA_LANGUAGE to the value only (currently en or de)

**Comment by kwierchris** [comment]
Should be done.
