### ISSUE TITLE
Introduce live preview for campaign content

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#233]
IFrame rendering for email templates, landing pages 
and also in campaign summary.

We need to store selected email temaplte id in campaign.
We need to store selected landing page id in campaign.

For each preview we need to be able to
* select it
* go to full tab browser preview

Email/Landing page should be using 1st available contact or dummy

**Comment by kwierchris** [comment]
Currently only *go to full tab browser preview* is missing.

**Comment by kwierchris** [comment]
Done
