### ISSUE TITLE
Add Campaign.LanguageId & Campaign.CountryId

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/onboarding#243]
Assuming a campaign targets suppliers in one language only
Add campaign.languageId. This allows us to generate the email in the language defined on campaign level.

Parent: OpusCapita/businessnetwork#36

**Comment by nczeranka** [comment]
https://github.com/OpusCapita/businessnetwork/issues/36

**Comment by kwierchris** [comment]
Please add the fields **languageId** and **countryId** to the campaign entity.

To understand what these fields will contain, have a look at:
* https://github.com/OpusCapita/isodata/wiki/language.model
* https://github.com/OpusCapita/isodata/wiki/Countries.endpoint

For the UI the campaign editor (components/CampaignForm.react.js ???) has to be extended. For this please use the external React components provided by the ISO-Data service.

**Comment by nczeranka** [comment]
Please provide a preselection of the language from the selection language of the current user.
