### ISSUE TITLE
Extend campaign editor for invitation code generation

### ISSUE THREAD

**Issue by kwierchris** [OpusCapita/onboarding#245]
Change the campaign editor (components/CampaignForm.react.js ???) to enable invitation code generation. Steps to take:

* Add an **invitationCode** field to the Campaign entity (UUIDv4).
* Add a checkbox to the UI labeled "Use invitation code for non-email media".
* When the checkbox gets checked, generate an invitation code in user/onboarddata with type *multipleUse* (requires OpusCapita/user#46) and use the field campaignDetails (requires OpusCapita/user#48) to store at least the campaign ID.
* Update the invitationCode field in Campaign to store the generated code.
* Display the generated invitation code in the campaign editor at the checkbox' position to enable users to copy it.
* If an invitation code has already been created and an existing campaign is edited, the checkbox for generation should be disabled. (You can not regenerate a new code.)

**Comment by kwierchris** [comment]
FYI:

Doing what we said above, you will not have the Campaign.id until the campaign was created. So in order to directly display the invitation code, you'll have to create the code (POST to user /onboardingdata) und update it later, when the Campaign.id was created by setting the *campaignDetails* property to an object containing the two fields below.

* id (Campaign.id)
* campaignId (Campaign.campaignId)

**Comment by nczeranka** [comment]
Sub-issue of OpusCapita/businessnetwork/issues/39

**Comment by nczeranka** [comment]
Prerequisite for OpusCapita/auth/issues/89
