### ISSUE TITLE
Create CampaignContact on event onboardingdata.created

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/onboarding#246]
Usage of multi-use invitationcodes implies that CampaignContacts are missing. To provide SupplierData for the customer, we have to create CampaignContacts for suppliers registrered with the multi-use invitationcode.

OpusCapita/user#50 determines whether the multi-use invitationcodes where used and fires proper events.
Onboarding has to create CampainContacts in case of 
* event onboardingdata.created

**Comment by nczeranka** [comment]
Parent issue: OpusCapita/businessnetwork#39

**Comment by kwierchris** [comment]
Events are now available: https://github.com/OpusCapita/user/wiki/Events
