### ISSUE TITLE
CampaignContact editor keeps old Contact when changing the Campaign

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/onboarding#260]
CampaignEditor has to be closed when opening another Campaign.
How to reproduce:
- Open a first campaign
- got to the Contacts (Step 2)
- select a contact for editing - but do nothing futher on this page.
- Open a second campaign
- go to the Contacts

As the result, the contact from the first campaign is still open in the editor. 
Example (contact with Id "supplier@example.com" is not part of current CampaignContacts!):
![grafik](https://user-images.githubusercontent.com/26661092/28773969-e2670764-75eb-11e7-808f-495cba304cf9.png)

**Comment by kwierchris** [comment]
Should be resolved by https://github.com/OpusCapita/onboarding/issues/269
