### ISSUE TITLE
CampaignContact import: support Contacts count > 3000

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/onboarding#265]
For DORMA we will receive Contacts import files with a count of approximatelly 3000.
Test showed that import of ~3000 contacts took about 1:15 minute.
But after 1 minute we show a "success" message to the user. 

Possitble actions:
- improve speed
- add some feedback to the user, like progress bar
  (any estimation possible?)
- asynchronous execution?
- ...

**Comment by celber** [comment]
Works. Takes ~1,5 minute. Loading mask would be cool :)
