### ISSUE TITLE
CampaignContact - List/Editor: Show either list or editor

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/onboarding#269]
Adjust search result list and the editor:
- Change the layout of the Contract list into one line -> complete width of the page.
- When selecting an entry for editing, open an overlay for the editor (not side by side with the list).
- Asure that old Contact data is not initially used when opening the Contact editor again.
Currently Contacts are initially shown when switching to another Campaign. This results for a big count of contacts in:
  - Wrong Contacts are shown while loading the correct ones
  - It slows down Campaigns with a low number of Contacts when switching from a high Contact count Campaign

**Comment by nczeranka** [comment]
Required by OpusCapita/businessnetwork#42

**Comment by kwierchris** [comment]
https://github.com/OpusCapita/onboarding/issues/281

**Comment by lasong** [comment]
https://github.com/OpusCapita/onboarding/pull/282
