### ISSUE TITLE
Enable circleci 2 cache

### ISSUE THREAD

**Issue by celber** [OpusCapita/onboarding#283]
CircleCi 2 got cache layer support. we can enable it to have build faster

https://circleci.com/docs/2.0/docker-layer-caching/

**Comment by nczeranka** [comment]
Requirements on usage of docker laying caching are not given: 
> Premium Feature ... for an additional fee. 
> To enable this feature, you must contact your Customer Success manager".

see https://circleci.com/docs/2.0/docker-layer-caching/

For this reason this changes are postponed for now.
