### ISSUE TITLE
Move tests container setup to buildscript.sh

### ISSUE THREAD

**Issue by celber** [OpusCapita/onboarding#284]
Move things like shared volume creation form circleci.yml to buildscript.sh

Linked to #146 #270

**Comment by celber** [comment]
@gr4per it works but output in circleCi is so huge it crashes my browser. Please see test build

**Comment by gr4per** [comment]
We need to create junit style test results xml file anyway for circle
So any verbose console output you could redirect to file and make available as build artifact….


Von: celber [mailto:notifications@github.com]
Gesendet: Dienstag, 15. August 2017 10:04
An: OpusCapita/onboarding <onboarding@noreply.github.com>
Cc: Gräper Arne <Arne.Graeper@opuscapita.com>; Mention <mention@noreply.github.com>
Betreff: Re: [OpusCapita/onboarding] Move tests container setup to buildscript.sh (#284)


@gr4per<https://github.com/gr4per> it works but output in circleCi is so huge it crashes my browser. Please see test build

**Comment by celber** [comment]
but this is not about tests. It is mostly bbuilding and downloading. Tests aren't big for now
