### ISSUE TITLE
Onboarding next steps

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#30]
1) email config via env
2) UI Flow: create campaign, select content (from available templates, this will be one only for now, but still), then select contacts, then start
we need to make this a guided flow as much as possible for the demo
3) onboarding page
here we know who it is (link from email) and need to somehow store this info in cookie or on client:
-company owning the campaign
-company of onboarded contact (for prepopulating fields)
-possibly some list of services (we dont have yet, so no worries)
Then we will use this as metadata during registration process

**Comment by theflexbird** [comment]
@gr4per is it done ? Did you write down a description of new behavior, so it can be closed ?

**Comment by gr4per** [comment]
This is indeed outdated, let's close.
We need a card for documenting the whole flow in wiki once done
