### ISSUE TITLE
Manual for supplier need to be accessible via landing page in the current language 

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#315]
in google drive
BES Offering / Business Network / 3. Agreement Documents / German
Manual_for_Suppliers_.....

- en: [Manual_for_Suppliers_ 2.0.2_Business_Network_Portal_20170721_1400.pdf](https://github.com/OpusCapita/onboarding/files/1231292/Manual_for_Suppliers_.2.0.2_Business_Network_Portal_20170721_1400.pdf)
- de: 
[Manual_for_Suppliers_ 2 0 3_Business_Network_Portal_20170725_15.26_EN_DE.pdf](https://github.com/OpusCapita/onboarding/files/1228220/Manual_for_Suppliers_.2.0.3_Business_Network_Portal_20170725_15.26_EN_DE.pdf)

----

We now have paths in blob:

    /blob/public/api/opuscapita/files/public/docs/Manual_for_Suppliers_.2.0.3_Business_Network_Portal_20170725_15.26_EN_DE.pdf
    /blob/public/api/opuscapita/files/public/docs/Manual_for_Suppliers_.2.0.2_Business_Network_Portal_20170721_1400.pdf

**Comment by celber** [comment]
Can i only ask for more detailed info where should it be visible and how should it look? @gr4per

**Comment by nczeranka** [comment]
Add a simple link on the landingpage (.../onboarding/public/landingpage/...) above the registration button.

**Comment by nczeranka** [comment]
New Documents
