### ISSUE TITLE
Onboarding Dashboard: too many CampaignContact requests

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/onboarding#320]
![pasted_image_at_2017_08_17_03_05_pm](https://user-images.githubusercontent.com/26661092/29417004-17e425fa-8368-11e7-9818-b78ab6e7a5b7.png)

We have to reduce the count of requests.
1. Analyzse which widget(s) requires so many requests.
2. Check for an optimization of the request count with existing REST interfaces. Is this is not possible, we have to discuss (an) extra service(s) that prepares the neccessary data on the server and provides only the results to the widget(s).

**Comment by kwierchris** [comment]
Basically fixed by https://github.com/OpusCapita/onboarding/pull/330
Additional issue created: https://github.com/OpusCapita/onboarding/issues/331
