### ISSUE TITLE
Search Campaigns: Result list not aligned

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/onboarding#325]
![grafik](https://user-images.githubusercontent.com/26661092/29454231-aae5cfa8-840c-11e7-880e-9f815333769f.png)

Even with a date range, then header do not fit to the data.

Additionally please check for this doubled horizontal rule between header and data. Should look like it is done in the CampaignContacts result list.

**Comment by celber** [comment]
Issue present in vendor library. We are using beta. Maybe we can wait 2-3 weeks till next more stable release? @nczeranka

**Comment by nczeranka** [comment]
If there is an issue in the lib, then provide details (link to vender ticket, etc.) about it.
Besides of it we have other result lists that work properly, like the CampaignContact list.
Please fix.

**Comment by theflexbird** [comment]
I was checking if there is a way to easy fix it. The answer is not. `react-bootstrap-table` lib has some limitations itself. It also not true CampaignContact list is displayed correctly.
<img width="1193" alt="zrzut ekranu 2017-08-25 o 11 56 59" src="https://user-images.githubusercontent.com/1525388/29709437-8d087cbc-898c-11e7-80ba-1c29ec4e224c.png">
I would like to propose using https://react-table.js.org/ in all places there react-bootstrap-table is present and style it separately.

**Comment by nczeranka** [comment]
Revised ui apporach from Chris
