### ISSUE TITLE
Onboarding dashboard has title "Campaign editor"

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/onboarding#342]
**Steps to reproduce:** 
1. Log in as a buyer (john.doe@ncc.com). 
2. Go to Suppliers->Onboarding dashboard

**Actual result:** 
The title is "Campaign editor". Also on the html source of the page there are some campaign editor related data.
**Expected result:** 
The title of the page is something like "Onboarding dashboard" and there is no campaign editor related javascript on the html page.
![image](https://user-images.githubusercontent.com/31001652/29811488-531fa52a-8cac-11e7-925f-3a2ea2b02d58.png)

**Comment by celber** [comment]
We are waiting for update/rewrite of react-menus

**Comment by nczeranka** [comment]
Should be fixed even more easily when using the new menu, which will be introduced soon.
