### ISSUE TITLE
"Registrierung"-button on the English landing page template

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/onboarding#343]
When creating a campaign in English, on the landing page template there is a registrierung-button shown. It is also shown on the actual landing page. 
![registrierung](https://user-images.githubusercontent.com/31001652/29814127-e93fed50-8cb4-11e7-95e4-85c5a488b4ae.PNG)

**Comment by nczeranka** [comment]
Fixed on Development. Publish to Prod is pending.
