### ISSUE TITLE
Campaign Contacts (Step 2) - Introduce fexible table component

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/onboarding#344]
Introduce new table component that supports:
- aligned layout
- flexible paging (here pagination on client side is enough)
- sorting (on all loaded data)
- filtering

We will start with the component proposed by Mateusz: https://react-table.js.org/#/story/readme

We will test the table component here (because we already have ~3000 Contacts at our customer), before it is implemented for #325 (and others), too.

**Comment by nczeranka** [comment]
Problems found:
- Editing entry: Updated data is not directly shown in the table.
- Update in editor is not closing the editor component.
- Can we add a drop down box for the filtering of status? (Consisting of all valid status)

Looks like a generel problem:
- Editing of entries without an email: Create button instead of Update - Seems that we are using the email and not the CampaignContact.Id as the primary key for Updates. -> extra ticket will be created.

**Comment by theflexbird** [comment]
Answers for questions:

Can we add a drop down box for the filtering of status?
**YES**
Can we adjust the way of the filtering? Eg. case insensitivity and or (implicit) wildcard search?
**YES, it is possible.**
Can we adjust the text in the buttons: "Previous"/"Next" -> "Previous page"/"Next page"?
**YES, very easy**
What about a selection of the page size? What is currently used?
**I disable it for purpose of this example. Normally it has dropdown. There can be also custom component for it.**

Most of the issues found are also present at _develop.businessnetwork.opuscapita.com_

**Comment by nczeranka** [comment]
Waiting on new ui from Christian.

**Comment by nczeranka** [comment]
belongs to #318
