### ISSUE TITLE
Menu Company -> Profile does not open on first click

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/onboarding#346]
Trying to open the Supplier Profile editor via Company -> Profile does not succeed on the first click.

![grafik](https://user-images.githubusercontent.com/26661092/29860315-0636472c-8d66-11e7-89fd-c6040c94d00f.png)

How to reproduce:
1. Go to Home (/bnp/sellerDashboard) or the Welcome page (/bnp/welcome)
2. Click on "Company" -> "Profile"
Only on the second click on the Menu item the Supplier Profile is opened.

**Comment by celber** [comment]
this ticket does not belong to onboarding. Fix was done 5 days ago in react-menus (master branch) and needs to be built on npm repository

**Comment by nczeranka** [comment]
Chris fixed the menu and updated refereces to @opuscapita/react-menus.
