### ISSUE TITLE
Contacts disappear from contact list if campaign's contacts view is reopened a few times

### ISSUE THREAD

**Issue by jarkinn** [OpusCapita/onboarding#350]
**Steps to reproduce:**

1. Create new campaign
2. Add one contact
3. Click Save and Proceed
4. Click Previous
5. Click Save and Proceed
6. Click Previous

**Actual result:**

Added contact is not visible anymore in the contact list.

**Expected result:**

Added contact should remain visible after going back and forth in the Campaign editor.

**Other information:**

The disappeared contacts come visible again if the contact editor is opened for some other campaign in between and after that reopen the view where the contacts had been lost.

**Comment by theflexbird** [comment]
Already fix in #344. Closing
