### ISSUE TITLE
Campaign - Cascaded deletion of CampaignContacts

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/onboarding#351]
Cascaded deletion of CampaignContacts is requested when deleting a Campaign.
Configuration done in #337 did not work properly. Therefore schema adjustements were removed, but you can see the history in the branch feature/337

Update from 2017.09.05:
Though migration to newer versions of Sequelize seems to be necessary, we decided to do the CampaignContact deletion manually without any schema adjustments.
Please review status of branch feature/337

**Comment by kekonen** [comment]
Update from 2017.09.05:
For automated deletion of CampaignContacts together with Campaign, there should be code added into a migration, which is mainly creates two Foreign Keys for both tables (the second one has an onDelete: Cascade) :
&nbsp;&nbsp;Up:
   ```
 const one = db.queryInterface.addConstraint('Campaign', ['id'], {
      type: 'FOREIGN KEY',
      name: 'custom_foreign_key',
      references: {
        table: 'CampaignContact',
        field: 'campaignId'
      }
    });

    const two = db.queryInterface.addConstraint('CampaignContact', ['campaignId'], {
      type: 'FOREIGN KEY',
      name: 'custom_foreign_key2',
      references: {
        table: 'Campaign',
        field: 'id'
      },
      onDelete: 'cascade'
    });
```

&nbsp;&nbsp;Down:
```
const one = db.queryInterface.removeConstraint('Campaign', 'daniils_custom_foreign_key');
const two = db.queryInterface.removeConstraint('CampaignContact', 'daniils_custom_foreign_key2');
```

The same time following code should be added at the end of Campaign.js:
```
  Campaign.hasMany(CampaignContact,
  {
      foreignKey : 'id',
      targetKey: 'campaignId'
  });

  CampaignContact.belongsTo(Campaign,
  {
     foreignKey : 'campaignId',
     targetKey: 'id',
     onDelete: 'cascade',
     hooks: true
  });
```

These editions have the following alternatives as queries:
```
ALTER TABLE `onboarding`.`Campaign` 
ADD CONSTRAINT `custom_foreign_key`
  FOREIGN KEY (`id`)
  REFERENCES `onboarding`.`CampaignContact` (`campaignId`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
```
```
ALTER TABLE `onboarding`.`CampaignContact` 
DROP FOREIGN KEY `custom_foreign_key2`;
ALTER TABLE `onboarding`.`CampaignContact` 
ADD CONSTRAINT `custom_foreign_key2`
  FOREIGN KEY (`campaignId`)
  REFERENCES `onboarding`.`Campaign` (`id`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;
```



The problem:
Sequelize lower than v4 gives this error:
`Unhandled rejection TypeError: db.queryInterface.addConstraint is not a function at Object.up (/home/node/onboarding/src/server/db/migrations/20444444444444-ondelete.main.js:9:35)`
which makes no sense, as the function **addConstraint** appears in official documentation.

The additions above should be tested.

**Comment by nczeranka** [comment]
Cascaded deletion is postponed, though we do not want to migrate to Sequelize 4 right now.
