### ISSUE TITLE
Voucher is generated once per instance

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#358]
The if (!count) condition doesn't work.
We reproduced it on prod with onboarding running two instances.
Result was that voucher was generated twice.

Revalidate condition. Once issue is fixed we can scale back to two instances on prod, but need successful test on dev first.

Please note that we must force the error condition as its a race condition by nature and not being able to reproduce with one try doesnt mean the issue is fixed.

**Comment by nczeranka** [comment]
part of #486

**Comment by kekonen** [comment]
By this moment, this issue is covered with https://github.com/OpusCapita/onboarding/pull/484 and absorbed by major transition from 'registered' to 'serviceConfig', which is now one transition. Now, voucher  is more of a legacy feature and will be removed soon.
