### ISSUE TITLE
updateTransitionState doesn't protect against multiple entry

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#366]
The function is used to in email generation. However, this can run parallel on multiple instances of onboarding.
In order to make it safe this needs to ensure transition is only execute in case contact status = expected status and update in one atomic operation
using Update set status = newStatus where status = oldStatus
or using lastModified timestamp.

**Comment by gr4per** [comment]
when refactoring the updateTransition, make sure to use internal api that also logs the transition,
see https://github.com/OpusCapita/onboarding/issues/169

**Comment by nczeranka** [comment]
part of #486

**Comment by kekonen** [comment]
Now, in this issue is covered in #486 . 
Multiple instances are supported by using Rabbit event queue. 
Current operation executed between InvitationGenerated and Sent transition states, which happen to follow one another, without intermediate states ('sending')
