### ISSUE TITLE
Photo of the landing page is cropped. 

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/onboarding#387]
**Steps to reproduce:** 
1. Create a campaign and change the "photo.png" so that it looks good (or in this case almost good) on the "Choosing landingpage template" view. 
![image](https://user-images.githubusercontent.com/31001652/30806769-caaae15a-a1ff-11e7-8742-8887c1851ef4.png)
2. Check the actual landing page. 
![image](https://user-images.githubusercontent.com/31001652/30806700-78cf0596-a1ff-11e7-840a-73c1fb5ab94f.png)

**Expected result:**
The photo on the landing page looks the same as on the "choosing landingpage template" 
**Actual result:** 
The photo on the landing page is cropped differently. 
**Other info:** 
- Picture that was used here had dimensions 504*193. Also tried with an image with dimensions 930*211, and also it looked totally different on different pages. 
- Also it was not told for the user what the dimensions of the photo should be. It was quite frustrating to try to find a correct-sized picture that was not cropped already on the choosing landingpage template-page. 
- While changing the picture of campaigns I also got the "choosing landingpage template" so messed up that it didn't show any pictures. Not sure how it was reproduced.

**Comment by nczeranka** [comment]
We told our first customer to exactly provide. I think it was:
- logo width 180px
- header images: 700px
- banner: height 200px

But it is no longer important, though we have the customized templates within an template editor now (already available on the develop system.)

I would propose to close the ticket.
