### ISSUE TITLE
Customer not able to open landing page

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#391]
https://businessnetwork.opuscapita.com/onboarding/public/landingpage/c_dekabank/initial/9890?transition=loaded

{"error":"unexpected error in update: TypeError: Cannot read property 'allowed' of undefined"}

Just reproduced by myself in Edge
https://businessnetwork.opuscapita.com/kibana/app/kibana#/doc/bnp_logs/bnp_logs/gateway?id=AV7IFeMDD5oq41izk7h4&_g=()

**Comment by nczeranka** [comment]
Supplier already used the invitation url.
Reusage of one invitation is not allowed. A better error message will be provided as part of #393
