### ISSUE TITLE
Error on CampaignContact status change possible

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/onboarding#393]
When trying to re-use an Campaign invitation email (= Trying to register with the same email invitation a second time, although somebody already registered for this CampaignContact.invitationCode), opening the landingpage restuls in
> {"error":"unexpected error in update: TypeError: Cannot read property 'allowed' of undefined"}

Error appears in `workflowConstants.js`.
No proper log found in Kibana. 
Please improve.

**Comment by kekonen** [comment]
Went through the process of campaign creation ("single use" camp.), registration of a client with invitation.
When I try to re-use the invitation code I get a normal reaction: "Invalid invitation code."

![image](https://user-images.githubusercontent.com/11177808/32110212-45b9ac64-bb37-11e7-86d7-9c7a40533fec.png)

**Comment by nczeranka** [comment]
This ticket is about using the same invitaitation (CampaignContact.invitationCode) more then once. Not about the UserAuth.verificationToken. Ticket description was adjusted.

**Comment by kekonen** [comment]
![image](https://user-images.githubusercontent.com/11177808/59031172-3db62d80-8863-11e9-9ca5-a0bd7fbb48c4.png)
