### ISSUE TITLE
Language and country combobox language is not changed. 

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/onboarding#403]
1. Go to Edit Campaign page (first page) 
2. Change language. 
3. Check the language of the comboboxes Language and Country

**Expected result:** 
Language for those comboboxes is also changed. 
**Actual result:** 
Language is not changed. The countrys and languages are still in the "old" language.

**Comment by nczeranka** [comment]
I don't understand the use case.
Prefilling the language and country makes sense on Campaign creattion (which we plan to do via #308), but changing the language via menu (I guess you mean this) should not have any effect on an open editor anymore.

**Comment by blomqsu1** [comment]
This seems to work now as I thought it should... Closing the bug issue.
