### ISSUE TITLE
onboarding-ng issues

### ISSUE THREAD

**Issue by theflexbird** [OpusCapita/onboarding#406]
- ~~Lack of email/landing page template (missing components in step 3 and 4)~~
- Loading indicator working in cascade manner and covering the whole page
- ~~In campaign edit mode, invitation checkbox should not be active~~
- Campaign progress bar in edit mode should have different mouse indicator
- ~~Labels in add user form should be without dash~~
- ~~Cannot remove user from campaign~~
- ~~While editing contact data country is not saved.~~
- Creation of campaign not working at all. Problem with validation of Campaign Id and Description filed.
- ~~In campaign edit mode, dates are not updating(not saved).~~
- ~~Numer zero (0) in the table while loading campaigns.~~
- Sometimes going from step 1 to step 2 making two forms appearing.
<img width="1219" alt="zrzut ekranu 2017-10-09 o 15 34 44" src="https://user-images.githubusercontent.com/1525388/31341053-7ca9b01c-ad08-11e7-8375-a18e34a4af73.png">

**Comment by kwierchris** [comment]
Try now please...

**Comment by theflexbird** [comment]
New bugs:

- Url in campaign editor is not reflecting step on which user is.
- Campaign editor is generating multiple invitation codes for one campaign (each time when you click on the checkbox). Previously it was remembering last generated invitation code and using it if the checkbox was checked.

**Comment by nczeranka** [comment]
Campaign handling was refactored.
