### ISSUE TITLE
Improvements for NG branch

### ISSUE THREAD

**Issue by theflexbird** [OpusCapita/onboarding#407]
- Change whole Campaign creator/editor from if-else statement to HOC(Higher Order Components).
- Remove unused `import` form files and also unused variables.
- Clean package.json (e.g. instead of `history` we should use history from `react-router`).
- Using SetTimeout like this `setTimeout(() => router.push('/'), 2000);` is a bad approach.

**Comment by kwierchris** [comment]
To #1: This is meant to be more simple in terms of being able to understand the flow. I removed additional components by attention to make the flow more understandable and flexible and I do not want to add this complexity again.
