### ISSUE TITLE
Email is not sent to contact

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/onboarding#411]
1. Create a campaign and add a contact with valid email address. 
2. Select default templates for that campaign. 
3. Start the campaign. 
4. Check the status of the contact

**Expected result:** 
The status changes at some point to sent, and the email is sent. 
**Actual result:** 
The status changes from queued->generatingInvitation->invitationGenerated->sending->loaded (this is what I noticed while pressing refresh multiple times, so there might be more states). No email is sent.

**Comment by nczeranka** [comment]
Problem appeared on development system only!
Please contact Chris before adjusting the code.
