### ISSUE TITLE
Web element IDs are missing

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/onboarding#415]
Most of the elements in onboarding are missing web element ids. Those ids are needed for test automation to make it stable. Now that the UI was changed it has taken 3 working days to fix the tests, because of missing web element ids.

**Comment by kwierchris** [comment]
We have to very careful with the usage of IDs as we may reuse components or using the same components multiple times on the same page which would resolve in a conflicting browser behavior.

**Comment by nczeranka** [comment]
Comment from Susanna via slack:
> ... Does that mean you don't know how to add the ids? I understand you have to be very careful, but it should be still possible to add some ids. Do you need help with that? I already asked one guy in Cash Management that has experience in IDs and he was will the help you if needed. They also have reusable components but they give the id as parameter when using the component.
