### ISSUE TITLE
Create new contact dialog should contain a scroll bar

### ISSUE THREAD

**Issue by jarkinn** [OpusCapita/onboarding#425]
For usability the Create new contact dialog should contain a scroll bar. Currently the lower part of the dialog goes out of the screen.

**Comment by kekonen** [comment]
@jarkinn do you still have the problem?

**Comment by jarkinn** [comment]
@kekonen Yes I still see the same issue

**Comment by jarkinn** [comment]
I have the problem in both Chrome and Firefox. Printscreen from the lower part of the dialog below (resolution 1920x1080). There is a scroll bar in the right side of the window but not in the dialog itself. The buttons are not visible to the user without scrolling the screen.

In order to improve usability, couldn't the scroll bar be on the dialog itself and the buttons be always visible to the user without scrolling the window?

![create_new_contact_dialog](https://user-images.githubusercontent.com/29628663/32729601-07d85a36-c88d-11e7-831d-bcfa5b8caa27.PNG)

**Comment by kwierchris** [comment]
This is the standard behavior of bootstrap. To change this, I think we would have to set things (dialog / dialog contents) to a fixed height which is not very responsive. We can try setting the height to some percentage value but I can guarantee that either people with a large screen or people with a very small screen will complain.

**Comment by jarkinn** [comment]
I discussed with our UX designers, who actually told me about this issue in the first place. Setting height to some percentage value is how it should be on their opinion. The implementation shouldn't remain like it is currently.

**Comment by nczeranka** [comment]
Replaced by BNP-49
