### ISSUE TITLE
Landing page preview is advancing workflow status

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#440]
![image](https://user-images.githubusercontent.com/22681804/32602761-a7200a1a-c547-11e7-97a5-b2d204335296.png)

Directly after starting the campaign I see all contacts already in "visited onboarding page"
Expectation is to see them in prep status or emailSent

Suspect loading landing page in preview could be causing this, but not clear why all contacts are impacted

**Comment by kwierchris** [comment]
Done
