### ISSUE TITLE
Fix language switch in Landing page template

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#443]
In Standard template support switching.

**Comment by blomqsu1** [comment]
In English version there is still a text "Haben Sie Fragen?"

**Comment by nczeranka** [comment]
Templates are stored in DB table Template. Demo-Data has to be adjusted to fulfil our requirements.

**Comment by nczeranka** [comment]
Subticket of  #471

**Comment by nczeranka** [comment]
Subticket of  #461
