### ISSUE TITLE
Cannot delete contact on Dev

### ISSUE THREAD

**Issue by kekonen** [OpusCapita/onboarding#482]
When I am trying to delete a contact on dev, im getting an error message just before the success message. An contact still exist afterwards. However, on local everything works as expected.
![image](https://user-images.githubusercontent.com/11177808/36733906-54c57660-1bd2-11e8-8516-8d998c0e1a82.png)

Upd: After sometime (cannot say what was the difference between attempts) I tried the same and it worked fine.

Upd 2: Same happened when I tryied to create a contact. In this case it was not added by the end of procedure.

Upd 3: This behavior is repeated for several times and in between, for some reason, everything was fine.

**Comment by kwierchris** [comment]
The question is: Is this a server side or a client side error?

**Comment by nczeranka** [comment]
Not reproduable.
