### ISSUE TITLE
CustomerId-TenantId clarification

### ISSUE THREAD

**Issue by kekonen** [OpusCapita/onboarding#498]
Related (implementation of CustomerId/SupplierId <-> TenantId conversion) : https://github.com/OpusCapita/useridentity-middleware/issues/10
Problem appeared in https://github.com/OpusCapita/onboarding/pull/484
CustomerId should be replaced with TenantId with help of (https://github.com/OpusCapita/useridentity-middleware/issues/10) in a number of cases:
1. ACL rules and endpoint definitions in template section.

**Comment by nczeranka** [comment]
see this.context.bouncer.getUserTenants(),
