### ISSUE TITLE
Importing of contacts fails

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/onboarding#504]
When trying to import contacts for a new campaign, there is an error: 403, {"message":"You do not have permissions to access the requested resource: /api/campaigns/jklj/contacts/import"}

**Other info:** 
Reproduced only in develop, not in stage.

**Comment by kekonen** [comment]
@blomqsu1 Fixed and tested. Please check.

**Comment by blomqsu1** [comment]
Tested and this works now.
