### ISSUE TITLE
Template saving permission issue

### ISSUE THREAD

**Issue by kekonen** [OpusCapita/onboarding#507]
Permissions issue (probably Blob) appears on onboarding while saving edited template. 
Though edited template is being properly saved.

To reproduce: 
Go to existing campaign or create the new one. Change to tab with template selection. Create a new one to be able to edit the one, or if there are editable one open it. Make some corrections in it and then press the Save button. You will see 
![image](https://user-images.githubusercontent.com/11177808/40120988-c7e0d9ba-5920-11e8-9472-3983c69335b6.png)

**Comment by nczeranka** [comment]
not reproduable anymore
