### ISSUE TITLE
Matching of contacts against network

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#52]
Assuming the contact list is generated by customer erp or other external system (salesforce) we would like to be sure we are not sending onboarding requests to already onboarded companies.
We could introduce a matching step that will actually 
- match company name (unexact match based on score)
- match any unique IDs provided
and propose double checking of any matches by the campaign owner.

**Comment by theflexbird** [comment]
I think matching by name will not work. Names of companies are not unique in global way. It would be better to distinguish them by tax number which is unique at least in country scale. What do you think @gr4per ?

**Comment by gr4per** [comment]
We can for sure match against country + country specific ids (tin, commercial register)
and the global unique ones like duns, vatid.
Matching the full Name only is not sufficient, I agree.
In any case, this will not be in scope of june milestone

**Comment by nczeranka** [comment]
Outdated.
In the meantime we are re-inviting companies and as part of the invitation new BusinessLink entries will be created.
