### ISSUE TITLE
Interesting race condition on prod

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#540]
We had to user.user.updated events for 
daniel.beaumont@jpmorgan.com

July 11th 2018, 11:25:28.474 | onboarding | info | - | - | processing user.updated event, user daniel.beaumont@jpmorgan.com, status emailVerified
-- | -- | -- | -- | -- | --
July 11th 2018, 11:25:28.476 | onboarding | info | - | - | processing user.updated event, user daniel.beaumont@jpmorgan.com, status registered
-- | -- | -- | -- | -- | --
July 11th 2018, 11:25:28.483 | onboarding | info | - | - | Executing (default): UPDATE `CampaignContact` SET `supplierId`='JPMorganSecuritiesPLC',`status`='needsVoucher' WHERE `status` IN ('loaded', 'registered') AND `userId` = 'daniel.beaumont@jpmorgan.com' AND `supplierId` IS NULL
-- | -- | -- | -- | -- | --
July 11th 2018, 11:25:28.500 | onboarding | info | - | - | Processed event user.updated of user daniel.beaumont@jpmorgan.com, nothing changed.
-- | -- | -- | -- | -- | --
July 11th 2018, 11:25:34.233 | onboarding | info | - | - | Calling service user with GET /onboardingdata/daniel.beaumont@jpmorgan.com.
-- | -- | -- | -- | -- | --
July 11th 2018, 11:25:34.256 | onboarding | info | - | - | user daniel.beaumont@jpmorgan.com has onboardData {"id":9515,"userId":"daniel.beaumont@jpmorgan.com","invitationCode":"856ac514-12f6-4ea9-8d09-43121db70faf","type":"multipleUse","tradingPartnerDetails":{},"serviceName":null,"campaignTool":"opuscapitaonboarding","campaignDetails":{"id":32,"campaignId":"neue-lieferanten"},"userDetails":{"email":"daniel.beaumont@jpmorgan.com","firstName":"Dan","lastName":"Beaumont"},"serviceDetails":null}going to try update...
-- | -- | -- | -- | -- | --
July 11th 2018, 11:25:34.257 | onboarding | info | - | - | Executing (default): UPDATE `CampaignContact` SET `status`='registered',`userId`='daniel.beaumont@jpmorgan.com' WHERE `invitationCode` = '856ac514-12f6-4ea9-8d09-43121db70faf' AND `status` = 'loaded'
-- | -- | -- | -- | -- | --
July 11th 2018, 11:25:34.265 | onboarding | info | - | - | Processed event user.updated of user daniel.beaumont@jpmorgan.com, nothing changed.
-- | -- | -- | -- | -- | --

Some conclusions:
* if not running in request context, but event driven, we should use the event.headers.correlationId as correlation Id and if not present event.messageId as correlationId 

* since first event for email verified includes an expensive API call to user to get onbaord data, it takes far longer to process it than second event

In order to fix it we must basically assert in registered event, that emailVerified event was already processed.
Problem is that we would need to load user onboard data, too in case we don't have the userId on the campaignContact already.

**Comment by nczeranka** [comment]
The described problem can't appear anymore (not needsVoucher state and many other changes) but nevertheless we should check for race conditions - especially in case of long lasting activities like the business-link creation.
