### ISSUE TITLE
Delete supplier data on event

### ISSUE THREAD

**Issue by kekonen** [OpusCapita/onboarding#547]
The service should listen for an event from supplier, which will clean up the service, and raise an event if needed.

https://github.com/OpusCapita/businessnetwork/issues/226

**Comment by nczeranka** [comment]
Nothing to delete. CampaignContacts belong to the Campaign and therefore the customer.
There could be a missunderstanding if suppliers got deleted though the contact still refers to the supplier, but how to solve it and is is a real use case, though supplier deletion is only used for testing purpose and will never be used in production systems.
