### ISSUE TITLE
Email sending fails on translation without setting error to contact

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#549]
To me it looks as if in 
const subject = translations[contact.Campaign.languageId || 'en']['eInvoiceSupplierOnboarding.email.subject'].replace(/{[\w|\d]*}/g, templateValues.customer.customerName);

the error is raised cause translations[contact.Campaign.languageId || 'en'] don't define the key
'eInvoiceSupplierOnboarding.email.subject'
The languageId being sv on campaign 191

This is not robust and must be fixed.
Unclear to me is also how campaignContact could be deleted without me finding 
"""
Executing (default): DELETE FROM `CampaignContact` WHERE `id` = '12447'
"""
log entry in kibana.

Hence I am not able to tell whether contact was successfully updated to error status. However, code looks like it doesnt even try to do that:
https://github.com/OpusCapita/onboarding/blob/develop/src/server/workflow/workflow.js#L228

So that needs fixing, too.

|September 7th 2018, 13:26:24.407 | onboarding | info | - | - | - | An error appeared while searching for contact with id '12447' TypeError: Cannot read property 'replace' of undefined     at sendMail (/home/node/onboarding/src/server/workflow/workflow.js:184:123)     at <anonymous> | -
-- | -- | -- | -- | -- | -- | -- | --|
| September 7th 2018, 13:26:24.279 | onboarding | info | - | - | - | Executing (default): SELECT `id`, `invitationCode`, `email`, `userId`, `campaignId`, `status`, `emailMessageId`, `companyName`, `contactFirstName`, `contactLastName`, `address`, `dunsNo`, `telephone`, `cell`, `supplierId`, `customerSupplierId`, `zipCode`, `city`, `country`, `pobox`, `commercialRegisterNo`, `taxIdentNo`, `vatIdentNo`, `lastStatusChange`, `serviceVoucherId`, `createdBy`, `changedBy`, `createdOn`, `changedOn` FROM `CampaignContact` AS `CampaignContact` WHERE `CampaignContact`.`id` = 12447; | - |
| September 7th 2018, 13:26:24.273 | onboarding | info | - | - | - | Rendering email for contact. (contactId : 12447) | -
| September 7th 2018, 13:26:24.270 | onboarding | info | - | - | - | Executing (default): SELECT `CampaignContact`.`id`, `CampaignContact`.`invitationCode`, `CampaignContact`.`email`, `CampaignContact`.`userId`, `CampaignContact`.`campaignId`, `CampaignContact`.`status`, `CampaignContact`.`emailMessageId`, `CampaignContact`.`companyName`, `CampaignContact`.`contactFirstName`, `CampaignContact`.`contactLastName`, `CampaignContact`.`address`, `CampaignContact`.`dunsNo`, `CampaignContact`.`telephone`, `CampaignContact`.`cell`, `CampaignContact`.`supplierId`, `CampaignContact`.`customerSupplierId`, `CampaignContact`.`zipCode`, `CampaignContact`.`city`, `CampaignContact`.`country`, `CampaignContact`.`pobox`, `CampaignContact`.`commercialRegisterNo`, `CampaignContact`.`taxIdentNo`, `CampaignContact`.`vatIdentNo`, `CampaignContact`.`lastStatusChange`, `CampaignContact`.`serviceVoucherId`, `CampaignContact`.`createdBy`, `CampaignContact`.`changedBy`, `CampaignContact`.`createdOn`, `CampaignContact`.`changedOn`, `Campaign`.`id` AS `Campaign.id`, `Campaign`.`description` AS `Campaign.description`, `Campaign`.`startsOn` AS `Campaign.startsOn`, `Campaign`.`endsOn` AS `Campaign.endsOn`, `Campaign`.`status` AS `Campaign.status`, `Campaign`.`campaignType` AS `Campaign.campaignType`, `Campaign`.`customerId` AS `Campaign.customerId`, `Campaign`.`campaignId` AS `Campaign.campaignId`, `Campaign`.`emailTemplate` AS `Campaign.emailTemplate`, `Campaign`.`landingpageTemplate` AS `Campaign.landingpageTemplate`, `Campaign`.`languageId` AS `Campaign.languageId`, `Campaign`.`countryId` AS `Campaign.countryId`, `Campaign`.`invitationCode` AS `Campaign.invitationCode`, `Campaign`.`createdBy` AS `Campaign.createdBy`, `Campaign`.`changedBy` AS `Campaign.changedBy`, `Campaign`.`createdOn` AS `Campaign.createdOn`, `Campaign`.`changedOn` AS `Campaign.changedOn`, `Campaign`.`config` AS `Campaign.config` FROM `CampaignContact` AS `CampaignContact` INNER JOIN `Campaign` AS `Campaign` ON `CampaignContact`.`campaignId` = `Campaign`.`id` WHERE `CampaignContact`.`id` = 12447 AND `CampaignContact`.`status` IN ('invitationGenerated'); | - |
| September 7th 2018, 13:26:24.266 | onboarding | info | - | - | - | Successful update, emmiting an event for 'onboarding.campaignContact.updated.invitationGenerated' for contact with id 12447 |

**Comment by nczeranka** [comment]
Deletion of the CampaignContacts were done manually via SQL on request by the project manager.
This problem will be fixed by using the cascaded supplier deletion - see OpusCapita/businessnetwork/issues/226

**Comment by nczeranka** [comment]
The problem with the translation raises, hough translation for SV exist, but not direclty for the requested key, but for a JSON structure that fits to the key only. Usually this is no problem, though the i18n manger supports both ways of translation files and has a fallback included. But here we did not use the i18n manager.
Problem is fixed by using the i18n manager.
