### ISSUE TITLE
Return back to customer connections after configuring the service

### ISSUE THREAD

**Issue by OKSALTA1** [OpusCapita/onboarding#564]
Supplier should not have to navigate back to customer connections after configuring the service. Supplier should be guided directly back to customer connections.

**Comment by nczeranka** [comment]
How to achieve this, though the supplier might want to configure up to three differenct in-channels (key-in, einvoice, pdf)?

**Comment by OKSALTA1** [comment]
If only one service to select from, you should be guided back to customer connections.

**Comment by nczeranka** [comment]
Has to be solved in einvoice-send. BusinessPartner will be introduced in short terms.
