### ISSUE TITLE
All necessary information to be filled in the company registration phase

### ISSUE THREAD

**Issue by OKSALTA1** [OpusCapita/onboarding#565]
Suppliers who are configuring the Key in/PO flip still have to separately navigate to the Company information tab and include their address information as well as bank account information in order to utilize the key in /PO flip. Currently the supplier is not automatically guided to do so in the onboading process. Although they are instructed so in the service configuration and in the user guide that step might be forgotten.

Supplier should be able to fill in all necessary information in the company registration phase.
-	Default address**
-	Bank account (IBAN+BIC, BankGiro, PlusGiro)**

**This information is required if Key in / PO flip functionality will be taken into use

**Comment by nczeranka** [comment]
BNP & Supplier service (in short terms: BusinessPartner) are responsible for supplier registration.
