### ISSUE TITLE
Onboard Punchout suppliers

### ISSUE THREAD

**Issue by OKSALTA1** [OpusCapita/onboarding#579]
Currently the Punchout supplier onboarding is done totally manually by contacting supplier and asking for them to provide necessary information. 

The Punchout suppliers should be able to onboard as automatically as possible utilizing BNP and campaign tool.
Campaign tool: New check box for Puncout under Catalog provisioning.

Registration: After registration and service configuration they will be asked to enter the OCI details:

1) External Shop URL for Punch-out call
2) Protocol used (https info
3) Expected method of parameters receiving: Selectable: drop down either POST or GET
4) Unique customer parameters 'login' and 'password’
5) What OCI functions are supported  
Select boxes: Validate, Detail, Sourcing, background search 
6) Other required parameters names and values (Free text box)

**Comment by OKSALTA1** [comment]
![image](https://user-images.githubusercontent.com/33858206/49155186-fa628b80-f322-11e8-8fb9-835f5fe1ff38.png)

**Comment by nczeranka** [comment]
You placed it in the ui as part of the master data maintenance -> this is another service: bnp(?)

- How should the workflow look like? Who is triggered with this information?
I don't know of any automated setup possibilities in eProc (SSM/PIM) or other external Products. Has to be done manually on SSM/PIM side in any case.
- What about additional open configuration parameters, like:
  - encoding of the supplier shop
  - customer specific credentials
  - customer specific parameters for the Outbound URL - e.g. for views (maybe multiple)
  - customer specific requirements for e.g. 
    - taxes
    - unit of measures (probably a mapping is needed)
    - classifications (probably a mapping is needed)
    - other fields...

**Comment by nczeranka** [comment]
moved to https://opuscapita.atlassian.net/browse/BNP-46
