### ISSUE TITLE
Email campaigning for customers

### ISSUE THREAD

**Issue by OKSALTA1** [OpusCapita/onboarding#580]
As a company I must be able to approach my suppliers and customers via email campaigns. The supplier side solution is there already but in order to be able to approach the customers the process must be created. Before we have the sell side products like invoice sending in please the campaigning would be for notifying the customers about new invoice sending channels e.g. we will only send electronic invoices. That’s why BNP should be possible to be used as a mass email sending marketing solution.
-	New campaign type customer onboarding
-	No Service Onboarding setup
-	No registration button in the landing page (and or possibility to enter the email address for email PDF's
-	Separate view in the campaign dashboard for the Customer campaigns.
-	Status only until visited landing page

**Comment by nczeranka** [comment]
moved to https://opuscapita.atlassian.net/browse/BNP-46
