### ISSUE TITLE
Use live data in onboarding dashboard

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#68]
Onboarding dashboard is showing mock data,
please change it to load real data from onboarding service.
onboarding/dashboard
and also bnp/dashboard

**Comment by celber** [comment]
[] Create card for each widget with info which data is needed in which widget

**Comment by theflexbird** [comment]
Are the certain cards were created ?

**Comment by celber** [comment]
No, it is about two cards on left. For cards on right you got all the data already

**Comment by celber** [comment]
sliced into "per widget" cards
