### ISSUE TITLE
Properly protect transition api

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#82]
Make transition api non-public by moving back to api/transition
For this, add new public endpoint invitationack/:campaignId/:contactId?transition=read

Both invitationack and landingpage need to be secured, i.e.
the uri after endpoint name has to be encrypted on server side
/:campaignId/:contactId?transition=read => some encypted hex code

This will make sure clients dont learn campaignId, contactId or transition, cannot guess on the api and most important cannot mess with the values without knowing the symmetric key.

On server endpoints, just take remainder of URI, unencrypt with secret and then use

**Comment by nczeranka** [comment]
Outdated. We are using the invitiationcode only.
