### ISSUE TITLE
Listen to user events

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#89]
https://github.com/OpusCapita/user/issues/2

Subscribe to events for status changes then
```
if status == created

Here we need to associate the userid with one of our campaignContacts if any.

Get onboardData by userid via rest call to user service

Get invitationCode from onboardData

If found and campaignTool == opuscapitaonboarding
db query to find campaignContact where invitationCode = ?
update this contact:
* status = user.status
* userId = userid from event
```

See here for updated UserOnboardData model:
https://github.com/OpusCapita/auth/issues/26

We also need to enhance model of CampaignContact to support userid

We also need to pass campaignTool and campaignDetails to Registration
https://github.com/OpusCapita/onboarding/issues/86

**Comment by celber** [comment]
Done *WITHOUT* campaignTool constraint
