### ISSUE TITLE
After loading external content in campaign email, contact status not updated

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#95]
As expected it need to be loaded
but it is stuck in sent.

Need test for this, too

**Comment by gr4per** [comment]
same after loading landing page. status still stuck in sent when it should be loaded

**Comment by gr4per** [comment]
April 27th 2017, 23:01:07.000	swarmMaster0	kong	info	109.44.3.234 - - [27/Apr/2017:21:01:06 +0000] "GET /onboarding/public/transition/testMeAgain/28?transition=read HTTP/1.1" 200 50 "-" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; Win64; x64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; McAfee; Microsoft Outlook 16.0.7369; Microsoft Outlook 16.0.7369; ms-office; MSOffice 16)"

according logs it executed read transition

**Comment by gr4per** [comment]
in db it seems correct, but ui is somehow showing stale info
![image](https://cloud.githubusercontent.com/assets/22681804/25504792/7a96249e-2b9f-11e7-8c6f-fb9cd3e1a4be.png)
![image](https://cloud.githubusercontent.com/assets/22681804/25504803/8ea9ec2c-2b9f-11e7-80d0-75c4ef519ba5.png)

**Comment by gr4per** [comment]
This doesnt reproduce anymore. So i would think we should just add a test to make sure and close card.

**Comment by gr4per** [comment]
not reproducing today on dev.

**Comment by celber** [comment]
tests to be made
