### ISSUE TITLE
I am not able to create Campaign

### ISSUE THREAD

**Issue by theflexbird** [OpusCapita/onboarding#97]
Screen shows the problem.
![zrzut ekranu z 2017-05-09 08-08-29](https://cloud.githubusercontent.com/assets/1525388/25837685/3c7301d4-348f-11e7-8326-8da0707e9201.png)

As you can see it is pretty unique id. It is also showing two boxes with opposite informations.

**Update**. It is connected to user session timeout

**Comment by celber** [comment]
ok, so you were not be able to create a campaign after session timed out. This is fine. Can be closed. Logging out after timeout is not connected to onboarding, it is done in api-gw
