### ISSUE TITLE
Implement "Create New Template" button functionality

### ISSUE THREAD

**Issue by theflexbird** [OpusCapita/onboarding#98]
At http://52.233.155.169/onboarding/edit/matmat204/template/email
After choosing email template and clicking "Create New Template" nothing is happening.

**Comment by gr4per** [comment]
Product level card for this: 
https://github.com/OpusCapita/businessnetwork/issues/15

Related cards:
https://github.com/OpusCapita/businessnetwork/issues/14
https://github.com/OpusCapita/onboarding/issues/110

**Comment by celber** [comment]
Took as patryk is no more with us

**Comment by celber** [comment]
assigning to graper, he wanted it
